config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'signup', to: 'users#new'
  get 'progr', to: 'tasks#progr'
  get 'free', to: 'tasks#free'
  get 'misc', to: 'tasks#misc'

  root 'pages#index'
  get 'tasks/newTask'
  get 'new_task', to: 'tasks#newTask'

  get 'login', to: 'sessions#new'
  resources :users, except: [:new]
  post 'login', to: 'sessions#create'
delete 'logout', to: 'sessions#destroy'
  resources  :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
 has_secure_password
 validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
 VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
 validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false },
 format: { with: VALID_EMAIL_REGEX }
 before_save { self.email = email.downcase }
 has_many :tasks

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  protect_from_forgery with: :exception

def current_user
     @current_user ||= User.find(session[:user_id]) if session[:user_id]
end

def logged_in?
   !!current_user
  end

  def require_user
     if !logged_in?
      redirect_to root_path
     end
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
 def index
   if !logged_in?
     redirect_to login_url
   end

 end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
 end

 def create
   user = User.find_by(email: params[:session][:email].downcase)
   if user  && user.authenticate(params[:session][:password])
    session[:user_id] = user.id
    redirect_to tasks_path(user)
   else

    render 'new'
   end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
   end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
before_action :set_task, only: [:edit, :update, :show, :destroy]

  def newTask
    @task = Task.new
  end
  def index
    @task = Task.all
  end

  def progr
    @progr = Task.where("subject = 'study'")
    @task = @progr
    render 'index'
  end

  def free
    @free = Task.where("subject = 'free'")
    @task = @free
    render 'index'
  end

  def misc
    @misc = Task.where("subject = 'misc'")
    @task = @misc
    render 'index'
  end
# helper_method :study

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  def update
    if @task.update(task_params)
      redirect_to task_path(@task)
    else
      render 'edit'
    end
  end

  def create
      @task = Task.new(task_params);
      @task.user = current_user
   if @task.save
     redirect_to task_path(@task)
   else
     render 'newTask'
   end
  end

  def edit
  end

  def show
  end

private

  def task_params
   params.require(:task).permit(:title, :due, :info, :progress, :subject)
  end

  def set_task
    @task = Task.find(params[:id]);
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def new
   @user = User.new
end

def create
  @user = User.new(user_params)
  if @user.save
   redirect_to root_path
  else
   render 'new'
  end
end
def edit
  @user = User.find(params[:id])
 end

 def update
  @user = User.find(params[:id])
  if @user.update(user_params)
   redirect_to tasks_path
  else
   render 'edit'
  end
 end

private
def user_params
  params.require(:user).permit(:username, :email, :password)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<nav>
  <a><%= link_to "Welcome Page", root_path %></a>
  <a><%= link_to "All Tasks", tasks_path %></a>
  <a><%= link_to "New Task", new_task_url %></a>
  <a><%= link_to "Logout", logout_path, method: :delete %></a>
</nav>

<h1 align="center" class="to_do" >To Do list</h1>
<h4 align="center" class="to_do" >the list of things to do</h4><br>
<h4 align="center" class="to_do" ><%= link_to "What things?", tasks_path %></h4>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
 <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
   <div class="panel panel-danger">
    <div class="panel-heading">
     <h2 class="panel-title">
      <%= pluralize(obj.errors.count, "error") %>
      prohibited this article from being saved:
     </h2>
     <div class="panel-body">
      <ul>
       <% obj.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
       <% end %>
      </ul>
     </div>
    </div>
   </div>
  </div>
 </div>
<% end %>

app/views/tasks/_form.html.erb
<%= render 'shared/errors', obj: @task  %>

<div class="row">
 <div class="col-xs-6 col-xs-offset-3 task">
  <%= form_for(@task, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <br>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :Task %>
   </div>
   <div class="col-sm-10">
    <%= f.text_field :title, class: "form-control", placeholder: "What do you need to do?" %>
   </div>
  </div>

  <div class="form-group">
   <div class="control-label col-sm-2">
     <%= f.label :due %>
   </div>
   <div class="col-sm-10">
    <%= f.text_field :due, rows: 10, class: "form-control", placeholder: "When is it due?" %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :"Progress" %>
   </div>
   <div class="col-sm-10">
    <%= f.text_area :progress, class: "form-control", placeholder: "What have you done?" %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :"Additional Info" %>
   </div>
   <div class="col-sm-10">
    <%= f.text_area :info, class: "form-control", placeholder: "Anything to add?" %>
   </div>
  </div>

  <div class="form-group">
    <div class="control-label col-sm-2">
     <%= f.label :"Choose a category" %>
    </div>
    <div class="control-label col-sm-6">
    <%= f.radio_button :subject, 'study' %>
    <%= f.label :subject, 'Programming' , :value => "study" %>
    <%= f.radio_button :subject, "misc" %>
    <%= f.label :subject, 'Other Uni Tasks' ,:value => "miscellaneous"%>
    <%= f.radio_button :subject, "free" %>
    <%= f.label :subject, 'Free Time' ,:value => "free" %>

  </div>
</div>

  <div class="form-group">
   <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit class: 'btn btn-primary btn-large btn-default' %>
   </div>
  </div>

<% end %>
 </div>
</div>

app/views/tasks/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

app/views/tasks/index.html.erb
<nav>
  <a><%= link_to "Welcome Page", root_path %></a>
  <a><%= link_to "All Tasks", tasks_path %></a>
  <a><%= link_to "New Task", new_task_url %></a>
  <a><%= link_to "Logout", logout_path, method: :delete %></a>
</nav>

</table>
<h1 align="center" class="to_do" >TO DO</h1>
<nav>
  <a><%= link_to "All Tasks", tasks_path%></a>
  <a><%= link_to "Programming Tasks", progr_path , method: :post%></a>
  <a><%= link_to "Other Uni Tasks", misc_path, method: :post %></a>
  <a><%= link_to "Free Time Tasks", free_path, method: :post%></a>
</nav>

<% @task.each do |task| %>

 <div class="row">
  <div class="col-xs-6 col-xs-offset-3 task">
    <div class="inline">
      <div class="">
        <%= link_to "Edit", edit_task_path(task), class: "btn btn-xs btn-default" %></div><br>
     <div class="">
       <%= link_to "Delete", task_path(task), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-default" %>
     </div>
    </div>
   <div class="inline">
    <div class="article-title ">
     <%= link_to task.title, task_path(task) %>
    </div>
    <div class="article-body">
      <p class="DUE">Due: <%= task.due %></p>
    </div>
   </div>
   <div class="">
     <div class="article-body">
     <p class="tit">About: </p> <%= truncate(task.info, length: 100) %>
    </div>
    <div class="article-body">
      <p class="tit ">Progress:</p>
    <%= truncate(task.progress, length: 100) %>
   </div>
   </div>
   <hr>
   <div class="article-meta-details">
           <small>Created by: <%= task.user.username if task.user %>,
                     <%= time_ago_in_words(task.created_at) %> ago,
                     last updated: <%= time_ago_in_words(task.updated_at) %> ago</small>
           </div>
  </div>
 </div>
 <br>
<% end %>

app/views/tasks/newTask.html.erb
<h1 align="center" class="to_do" >Need something done? </h1><br>
<%= render 'form' %>

<% if @task.errors.any? %>
 <h2>The following errors prevented the article from saving:</h2>
 <ul>
 <% @task.errors.full_messages.each do |msg|%>
 <li><%= msg %></li>
 <% end %>
 </ul>
<% end %>

app/views/tasks/show.html.erb
<h2 align="center">Title: <%= @task.title %></h2>

<div class="panel panel-default col-xs-6 col-xs-offset-3"><br>
  <%= link_to 'Back', tasks_path, class: "btn btn-xs btn-default" %>
  <%= link_to "Edit", edit_task_path(@task), class: "btn btn-xs btn-default" %>
  <%= link_to "Delete", task_path(@task), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-default" %>
  <div class="article-body">
    <p class="DUE">Due: <%= @task.due %></p>
  </div>
<div class="">
  <div class="article-body">
  <p class="tit">About: </p> <%= simple_format(@task.info) %>
 </div>
 <div class="article-body">
   <p class="tit ">Progress:</p>
 <%= simple_format(@task.progress) %>
</div>
</div>
<div class="article-meta-details">
        <small>Created by: <%= @task.user.username if @task.user %>,
                  <%= time_ago_in_words(@task.created_at) %> ago,
                  last updated: <%= time_ago_in_words(@task.updated_at) %> ago</small>
        </div>
</div>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<div class="row">
 <div class="col-xs-6 col-xs-offset-3 task">
   <br>
  <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :username %>
   </div>
   <div class="col-sm-8">
    <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :email %>
   </div>
   <div class="col-sm-8">
    <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :password %>
   </div>
   <div class="col-sm-8">
    <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
   </div>
  </div>
  <div class="form-group">
   <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit(@user.new_record?  ? "Sign up" : "Update account", class: 'btn btn-primary btn-large') %>
   </div>
  </div>
<% end %>
 </div>
</div>

app/views/users/edit.html.erb
<h1 align="center to_do">Edit User Account</h1>
<%= render 'form' %>

app/views/users/new.html.erb
<h1 align="center">Signup</h1>
<%= render 'form' %>